### ISSUE TITLE
Dependencies fail to download with no error

### ISSUE THREAD

**Issue by 0xtf** [Widen/cloudfront-auth#19]
Hi,

I was trying to run this on Ubuntu 18.04 with nodesource 11 packages. Somehow the .ZIP is created without any errors. 

I noticed, while troubleshooting the Lambda function, that it appears some modules are missing when the function is uploaded. 

Sample output from Lambda test:

```
error: Error
    at Error (native)
    at Object.fs.openSync (fs.js:641:18)
    at Object.fs.readFileSync (fs.js:509:33)
    at Object.Module._extensions..js (module.js:578:20)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
```

When running/building the ZIP on Docker with latest node image it works fine. 

I'll update this issue later one with output from both 18.04 with Nodesource vs Docker.

**Comment by 0xtf** [comment]
Did a clean installation of everything and no longer had a problem! Closing the issue. Sorry for the noise and thank you for the great project and support!

**Comment by payton** [comment]
No problem! Glad you were able to get it working.
