### ISSUE TITLE
Cannot find module 'colors/safe'

### ISSUE THREAD

**Issue by obazoud** [Widen/cloudfront-auth#7]
Try to build this project but `colors` module is missing:

```
 % ./build.sh

> cloudfront-auth@1.0.0 build /home/obazoud/xxx/xxx/code/playground/cloudfront-auth
> npm install && cd build && npm install && cd .. && node build/build.js

cookie@0.3.1 node_modules/cookie

nonce@1.0.4 node_modules/nonce

url@0.11.0 node_modules/url
├── punycode@1.3.2
└── querystring@0.2.0

jwk-to-pem@1.2.6 node_modules/jwk-to-pem
├── safe-buffer@5.1.1
├── asn1.js@4.10.1 (minimalistic-assert@1.0.0, inherits@2.0.3, bn.js@4.11.8)
└── elliptic@6.4.0 (minimalistic-assert@1.0.0, inherits@2.0.3, brorand@1.1.0, minimalistic-crypto-utils@1.0.1, hmac-drbg@1.0.1, bn.js@4.11.8, hash.js@1.1.3)

jsonwebtoken@8.2.0 node_modules/jsonwebtoken
├── lodash.isplainobject@4.0.6
├── lodash.isboolean@3.0.3
├── lodash.isinteger@4.0.4
├── lodash.isnumber@3.0.3
├── lodash.isstring@4.0.1
├── lodash.once@4.1.1
├── ms@2.1.1
├── lodash.includes@4.3.0
├── xtend@4.0.1
└── jws@3.1.4 (safe-buffer@5.1.1, base64url@2.0.0, jwa@1.1.5)

axios@0.17.1 node_modules/axios
├── is-buffer@1.1.6
└── follow-redirects@1.4.1 (debug@3.1.0)
npm WARN package.json cloudfront-auth-build@1.0.0 No repository field.
npm WARN package.json cloudfront-auth-build@1.0.0 No README data
url@0.11.0 node_modules/url
├── punycode@1.3.2
└── querystring@0.2.0

node-rsa@0.4.2 node_modules/node-rsa
└── asn1@0.2.3

axios@0.17.1 node_modules/axios
├── is-buffer@1.1.6
└── follow-redirects@1.4.1 (debug@3.1.0)

prompt@1.0.0 node_modules/prompt
├── revalidator@0.1.8
├── pkginfo@0.4.1
├── colors@1.2.1
├── read@1.0.7 (mute-stream@0.0.7)
├── winston@2.1.1 (cycle@1.0.3, stack-trace@0.0.10, eyes@0.1.8, isstream@0.1.2, async@1.0.0, pkginfo@0.3.1, colors@1.0.3)
└── utile@0.3.0 (deep-equal@0.2.2, async@0.9.2, i@0.3.6, ncp@1.0.1, mkdirp@0.5.1, rimraf@2.6.2)

shelljs@0.8.1 node_modules/shelljs
├── interpret@1.1.0
├── glob@7.1.2 (path-is-absolute@1.0.1, inherits@2.0.3, fs.realpath@1.0.0, once@1.4.0, inflight@1.0.6, minimatch@3.0.4)
└── rechoir@0.6.2 (resolve@1.5.0)

ramda@0.25.0 node_modules/ramda
module.js:327
    throw err;
    ^

Error: Cannot find module 'colors/safe'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/obazoud/xxx/xxx/code/playground/cloudfront-auth/build/build.js:5:16)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)

npm ERR! Linux 4.13.0-36-generic
npm ERR! argv "/home/obazoud/.nvm/versions/node/v4.3.2/bin/node" "/home/obazoud/.nvm/versions/node/v4.3.2/bin/npm" "run-script" "build"
npm ERR! node v4.3.2
npm ERR! npm  v2.14.12
npm ERR! code ELIFECYCLE
npm ERR! cloudfront-auth@1.0.0 build: `npm install && cd build && npm install && cd .. && node build/build.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the cloudfront-auth@1.0.0 build script 'npm install && cd build && npm install && cd .. && node build/build.js'.
npm ERR! This is most likely a problem with the cloudfront-auth package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm install && cd build && npm install && cd .. && node build/build.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls cloudfront-auth
npm ERR! There is likely additional logging output above.
```

```
 % git rev-parse HEAD
28b853ef5bf2d4773ba5593fa8332c1b610c176f
```

**Comment by payton** [comment]
Are you able to run the commands
`npm install && cd build && npm install && cd .. && node build/build.js`
independently (`npm install` in root, `npm install` in build, and run `node build/build.js` from root)?

`colors@1.2.1` should have already been installed as it is a dependency for `prompt`.

I have not been able to reproduce this error, so we can start from here.

The only notable difference I can see at first glance is that you are on Ubuntu. I am currently running macOS Sierra.

**Comment by payton** [comment]
Following up on this issue. Did you have any luck finding a fix?

**Comment by payton** [comment]
I'm going to assume this issue has been resolved. Feel free to open it back up if needed.
